---
- name: AWS Slack Confirm
  hosts: localhost
  connection: network_cli
  gather_facts: no

  tasks:
    - name: SEND FIRST COMPLIANCE CONFIRM MESSAGE TO SLACK
      uri:
        url: "{{response_url}}"
        body: '{"text":"AWS Provisioning complete!"}'
        method: POST
        validate_certs: no
      delegate_to: localhost
      run_once: yes

    - name: SEND SECOND COMPLIANCE CONFIRM MESSAGE TO SLACK
      uri:
        url: "{{response_url}}"
        body: '{"text":"AWS Apache Web Server is reachable at {{public_ip}} "}'
        method: POST
        validate_certs: no
      delegate_to: localhost
      run_once: yes