- name: Install Apache and Deploy Website
  hosts: all
  become: true

  vars:
    httpd_packages:
      - httpd
      - mod_wsgi

  tasks:
    - name: install httpd packages
      yum:
        name: "{{ httpd_packages }}"
        state: present

    - name: create site-enabled directory
      file:
        name: /etc/httpd/conf/sites-enabled
        state: directory
            
    - name: copy apache directory
      copy:
        src: files/apache/
        dest: /var/www/html/
    
    - set_stats:
        data:
          public_ip: "{{ ansible_host }}"