- name: Install Apache and Deploy Website
  hosts: all
  become: true

  vars:
    packages:
      - httpd
      - mod_wsgi
      - firewalld

  tasks:
    - name: install  packages
      yum:
        name: "{{ packages }}"
        state: present

    - name: Ensure state of apache_services
      service:
        name: httpd
        enabled: yes
        state: started

    - name: Ensure state of firewalld
      service:
        name: firewalld
        enabled: yes
        state: started  

    - name: Ensure state of apache_ports
      firewalld:
        port: 80/TCP
        zone: public
        permanent: yes
        immediate: true
        state: enabled

    - name: create site-enabled directory
      file:
        name: /etc/httpd/conf/sites-enabled
        state: directory
            
    - name: copy apache directory
      copy:
        src: files/apache/
        dest: /var/www/html/
    
    - set_stats:
        data:
          public_ip: "{{ ansible_host }}"