- name: Teardown AWS Infrastructure
  hosts: localhost
  connection: local
  become: no
  gather_facts: no

  roles:
    - role: aws_infrastructure
      vars: 
        ec2_wait: no
        teardown: true
        state: absent